#!/bin/sh

# srcdir is the directory where this script resides
srcdir="$(cd `dirname "$0"` && pwd)"
progname="`basename "$0"`"
. ${srcdir}/env.sh

printf "${progname}: removing previous results... " > /dev/tty
rm -rf $resultdir
echo 'done.' > /dev/tty
